# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34dd8f87efbe417c7afe591cdcb5faa6d3a5fb4e1dd6c5b3ff3baaadb3875e09210b1161c9ac2ebeb5183d2c759218cfa9dacf9755461a3b9e31f972ccb451aa

test:
  secret_key_base: 1c3556c1a157b7afd20739d3dc48a513e7092ad2d17c369ae166e9e5a7e3b7874bfab4d24bf2290e3c6df44a70c727d27cfcf843e6afe84b5c51ce8b068beb43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
